### ISSUE TITLE
Re-enable Jenkins job

### ISSUE THREAD

**Issue by ajtucker** [ONS-OpenData/HMRC_RTS#5]
Job is currently disabled as the upload takes many hours. Need to check that the latest data (2018 currently) is properly converted and then re-enable the job.

Consider removing the git-push trigger. This transform should be run when new data is published.

This dataset could be a test case for better ways to update the data cube. Rather than remove the old data and upload again, we could upload just the new data to the cube.

**Comment by mikeAdamss** [comment]
@ajtucker - have made the other changes to this pipelines issues, but I'm wary of enabling all the things and trying it out given the above. So they're "done", but also not tested in anger.

am I alright to re-enable this and give it a whirl?

edit - discussed. It's in progress, Alex has pipeline changes to make.

**Comment by ajtucker** [comment]
Re-enabled Jenkins job. Pipeline issues are in #6
